# Data
quadtree = "qt_min10_max1000_df10pct.gml" # check available quadtrees in data/processed/LDoGI/quadtrees
data_fraction = 0.0002                    # 0.1 should be fine, for testing use 0.0001

# Model
layers = 50 # 18 | 34 | 50 | 101 | 152 !hyperparameter

# Training
batch_size = 32 # 32 | 64 | 128 !hyperparameter
optim = 'sgd'   # 'adam' | 'sgd' !hyperparameter
epochs = 10     # set to 50 and use early stopping
lr = 0.01       # 0.01 | 0.001 | 0.0001 !hyperparameter


# implement
# label smoothing
# MSE loss
# MSSE loss
